#!/bin/bash

# Script: Verificar Credenciais OAuth - Agende Mais
# Ajuda a identificar qual Client ID e Secret você deve usar

echo "═══════════════════════════════════════════════════════════"
echo "🔍 VERIFICAÇÃO DE CREDENCIAIS OAUTH - AGENDE MAIS"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "📋 PASSO 1: PEGAR CLIENT ID E SECRET DO GOOGLE CLOUD"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "1. Abra este link (Ctrl+Click):"
echo "   https://console.cloud.google.com/apis/credentials?project=project-966992499199"
echo ""
echo "2. Na seção 'OAuth 2.0 Client IDs', procure por:"
echo "   • 'Web client (auto created by Google Service)' OU"
echo "   • 'Client for Web application zapagenda-3e479'"
echo ""
echo "3. CLIQUE NO NOME do OAuth Client"
echo ""
echo "4. Você verá algo assim:"
echo ""
echo "   Client ID:"
echo "   966992499199-XXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com"
echo "                └─────────── COPIE ISSO! ─────────────┘"
echo ""
echo "   Client secret:"
echo "   GOCSPX-XXXXXXXXXXXXXXXXXXXXX"
echo "   └──────── COPIE ISSO! ────────┘"
echo ""
echo "5. ANOTE esses valores (você vai precisar no Passo 2)"
echo ""
read -p "Pressione ENTER quando tiver COPIADO os valores..."
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📋 PASSO 2: VERIFICAR FIREBASE AUTH"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "1. Abra este link:"
echo "   https://console.firebase.google.com/project/zapagenda-3e479/authentication/providers"
echo ""
echo "2. Clique no provedor 'Google'"
echo ""
echo "3. Na seção 'Web SDK configuration', você verá:"
echo "   • Web client ID: (valor atual)"
echo "   • Web client secret: (valor atual)"
echo ""
echo "4. Compare com os valores que você copiou no Passo 1"
echo ""
echo "   São IGUAIS?"
echo "   ├─ SIM → O problema está em outro lugar (veja Passo 4)"
echo "   └─ NÃO → Continue para o Passo 3"
echo ""
read -p "Pressione ENTER para continuar..."
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📋 PASSO 3: ATUALIZAR FIREBASE AUTH"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Se os valores do Passo 1 e Passo 2 são DIFERENTES:"
echo ""
echo "1. No Firebase Console (provedor Google), clique em EDITAR"
echo ""
echo "2. Cole os valores que você copiou do Google Cloud (Passo 1):"
echo "   • Web client ID: [cole aqui o Client ID do Passo 1]"
echo "   • Web client secret: [cole aqui o Client Secret do Passo 1]"
echo ""
echo "3. Clique em 'Salvar'"
echo ""
echo "4. Aguarde 2-3 minutos para propagar"
echo ""
read -p "Pressione ENTER quando tiver SALVO..."
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📋 PASSO 4: VERIFICAR URIs NO GOOGLE CLOUD"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Volte para o Google Cloud Console (OAuth Client):"
echo "https://console.cloud.google.com/apis/credentials?project=project-966992499199"
echo ""
echo "Verifique se TODOS esses URIs estão configurados:"
echo ""
echo "📍 Authorized JavaScript origins:"
echo "   ✓ https://zapagenda-3e479.firebaseapp.com"
echo "   ✓ https://zap-agenda.onrender.com"
echo "   ✓ http://localhost:3000"
echo ""
echo "📍 Authorized redirect URIs:"
echo "   ✓ https://zapagenda-3e479.firebaseapp.com/__/auth/handler"
echo "   ✓ https://zap-agenda.onrender.com/__/auth/handler"
echo "   ✓ http://localhost:3000/__/auth/handler"
echo ""
echo "Se algum estiver FALTANDO:"
echo "   1. Clique em 'ADD URI'"
echo "   2. Cole o URI faltante"
echo "   3. Clique em 'SAVE'"
echo ""
read -p "Pressione ENTER quando tiver VERIFICADO..."
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📋 PASSO 5: ATUALIZAR VARIÁVEIS NO RENDER.COM"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "⚠️  IMPORTANTE: As variáveis de ambiente CORRETAS são:"
echo ""
echo "GOOGLE_CLIENT_ID (do Google Cloud, Passo 1)"
echo "GOOGLE_CLIENT_SECRET (do Google Cloud, Passo 1)"
echo ""
echo "❌ NÃO confunda com:"
echo "   NEXT_PUBLIC_FIREBASE_* ← Essas são DIFERENTES!"
echo ""
echo "1. Abra: https://dashboard.render.com/"
echo "2. Clique no serviço 'zap-agenda'"
echo "3. Vá em 'Environment'"
echo "4. Procure por estas variáveis:"
echo ""
echo "   GOOGLE_CLIENT_ID"
echo "   GOOGLE_CLIENT_SECRET"
echo ""
echo "5. Se existirem, ATUALIZE com os valores do Passo 1"
echo "   Se NÃO existirem, ADICIONE:"
echo ""
echo "   Nome: GOOGLE_CLIENT_ID"
echo "   Valor: [Cole o Client ID do Passo 1]"
echo ""
echo "   Nome: GOOGLE_CLIENT_SECRET"
echo "   Valor: [Cole o Client Secret do Passo 1]"
echo ""
echo "6. Clique em 'Save Changes'"
echo "7. Aguarde o deploy automático (2-3 minutos)"
echo ""
read -p "Pressione ENTER quando o deploy terminar..."
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "🧪 PASSO 6: TESTAR"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "1. Aguarde 5 minutos após o deploy"
echo ""
echo "2. Abra uma JANELA ANÔNIMA (Ctrl+Shift+N)"
echo ""
echo "3. Vá em: https://zap-agenda.onrender.com/login"
echo ""
echo "4. Abra DevTools (F12) → Console"
echo ""
echo "5. Clique em 'Continuar com Google'"
echo ""
echo "6. O que aconteceu?"
echo "   ├─ ✅ Funcionou! → Problema resolvido!"
echo "   └─ ❌ Mesmo erro → Veja Troubleshooting abaixo"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "🔧 TROUBLESHOOTING"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Se ainda der erro 'invalid_client':"
echo ""
echo "Opção 1: RECRIAR O OAUTH CLIENT"
echo "─────────────────────────────────────"
echo "1. Google Cloud Console → Credentials"
echo "2. Clique nos 3 pontinhos do OAuth Client → DELETE"
echo "3. Clique em 'CREATE CREDENTIALS' → 'OAuth client ID'"
echo "4. Application type: 'Web application'"
echo "5. Name: 'zapagenda-web-client'"
echo "6. Adicione os URIs (Passo 4)"
echo "7. Clique em 'CREATE'"
echo "8. COPIE o novo Client ID e Secret"
echo "9. ATUALIZE no Firebase (Passo 3)"
echo "10. ATUALIZE no Render (Passo 5)"
echo ""
echo "Opção 2: VERIFICAR DOMÍNIO AUTORIZADO"
echo "──────────────────────────────────────"
echo "1. Google Cloud Console → OAuth consent screen"
echo "2. Clique em 'EDIT APP'"
echo "3. Role até 'Authorized domains'"
echo "4. Adicione: zapagenda-3e479.firebaseapp.com"
echo "5. Adicione: zap-agenda.onrender.com"
echo "6. Clique em 'SAVE AND CONTINUE'"
echo ""
echo "Opção 3: VERIFICAR STATUS DE PUBLICAÇÃO"
echo "────────────────────────────────────────"
echo "1. Google Cloud Console → OAuth consent screen"
echo "2. Se 'Publishing status' = 'Testing':"
echo "   → Clique em 'PUBLISH APP'"
echo "   → Confirme"
echo "3. Aguarde 5 minutos e teste novamente"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📝 RESUMO DAS VARIÁVEIS"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "No Render.com, você DEVE ter:"
echo ""
echo "# Credenciais do Google OAuth (Google Cloud Console)"
echo "GOOGLE_CLIENT_ID=966992499199-XXXXXXXXXXXX.apps.googleusercontent.com"
echo "GOOGLE_CLIENT_SECRET=GOCSPX-XXXXXXXXXXXXXXXXXXXXX"
echo ""
echo "# Configuração do Firebase (Firebase Console)"
echo "NEXT_PUBLIC_FIREBASE_API_KEY=AIza..."
echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=zapagenda-3e479.firebaseapp.com"
echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=zapagenda-3e479"
echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=zapagenda-3e479.firebasestorage.app"
echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=966992499199"
echo "NEXT_PUBLIC_FIREBASE_APP_ID=1:966992499199:web:..."
echo ""
echo "# Service Account (para server-side)"
echo "FIREBASE_SERVICE_ACCOUNT_KEY={...json...}"
echo ""
echo "# URL do app"
echo "APP_BASE_URL=https://zap-agenda.onrender.com"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "✅ CONCLUÍDO!"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Se seguiu TODOS os passos e ainda não funciona:"
echo ""
echo "1. Tire screenshots de:"
echo "   • OAuth Client no Google Cloud (URIs configurados)"
echo "   • Provedor Google no Firebase (Client ID mascarado)"
echo "   • Variáveis de ambiente no Render"
echo "   • Erro completo no console do navegador"
echo ""
echo "2. Mande aqui para análise detalhada"
echo ""
echo "═══════════════════════════════════════════════════════════"
